### ISSUE TITLE
Is it possible to define nested variables for evaluation?

### ISSUE THREAD

**Issue by vlad-ivanov-name** [martinohmann/hcl-rs#150]
Hello, thank you for the awesome library!

I tried to look around but couldn't find this: is it possible to define nested identifiers and objects when evaluating with `hcl::eval::Context`?

For example, I'd like to evaluate the value of the following property:

```
  stages = stage.project_test.id
```

So I would need to make `stage` object available to context, then I would need to add `project_test` property, etc. Pretty much the same way it's done in terraform

**Comment by martinohmann** [comment]
Hi @vlad-ivanov-name,

your use case is already supported, just use a nested map and serialize it as a `hcl::Value` via `hcl::to_value(map)`.

Here is a example (i'm using `IndexMap` here, but other maps like `HashMap` will also do):

```rust
use hcl::eval::Context;
use indexmap::indexmap;
use serde::Deserialize;

#[derive(Deserialize, Debug, PartialEq, Eq)]
struct Config {
    stages: u64,
}

let variables = indexmap! {
    "stage" => indexmap! {
        "project_test" => indexmap! {
            "id" => 1,
        }
    }
};

let mut ctx = Context::new();
for (name, value) in variables {
    ctx.declare_var(name, hcl::to_value(value).unwrap());
}

let input = "stages = stage.project_test.id";

let config: Config = hcl::eval::from_str(input, &ctx).unwrap();

assert_eq!(config, Config { stages: 1 });
```
It's also possible to do this with a map of structs or even just a struct as long as the struct implements `Serialize`:

```rust
use hcl::eval::Context;
use pretty_assertions::assert_eq;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Deserialize, Debug, PartialEq, Eq)]
struct Config {
    stages: u64,
}

#[derive(Serialize)]
struct Stage {
    id: u64,
}

let mut stages = HashMap::new();
stages.insert("project_test", Stage { id: 1 });

let mut ctx = Context::new();
ctx.declare_var("stage", hcl::to_value(stages).unwrap());

let input = "stages = stage.project_test.id";

let config: Config = hcl::eval::from_str(input, &ctx).unwrap();

assert_eq!(config, Config { stages: 1 });
```

**Comment by martinohmann** [comment]
I'm planning to add some testable examples for use cases like this, but I'm currently short on time, so not sure when I will get to this.
