### ISSUE TITLE
Namespaced functions

### ISSUE THREAD

**Issue by MicaiahReid** [martinohmann/hcl-rs#335]
The official hcl repo now supports namespaced functions (as of [this PR](https://github.com/hashicorp/hcl/pull/639)). Is there any plan to support that here? This is what I'd like to be able to do:

```hcl
block "foo" "bar" { 
  foobar = namespace::some_function() 
}
```

**Comment by martinohmann** [comment]
Thanks for the hint. I also recently stumbled across this but forgot to create an issue for that myself. I want to support this, especially now that this also landed in terraform. I'm going to read up on the specifics in the next few days and will try to implement it.

**Comment by MicaiahReid** [comment]
Beautiful, thanks @martinohmann!

**Comment by martinohmann** [comment]
@MicaiahReid I just released support for namespaced functions in `hcl-edit` 0.8.0 and `hcl-rs` 0.17.0. This required some breaking changes, see the linked PR for more information.
