### ISSUE TITLE
create `hcl::value::from_value` function just like `hcl::value::to_value`

### ISSUE THREAD

**Issue by zkonge** [martinohmann/hcl-rs#345]
hi, I want to deserialize `hcl::Value` into my type `T`, but after reading through the code, I only found the `hcl::value::to_value`.

Is there any special reason execluding the `from_value`?

```rust
pub fn from_value<'de, T>(value: Value) -> Result<T>
where
    T: Deserialize<'de>,
{
    T::deserialize(ValueDeserializer::new(value))
}
```

**Comment by martinohmann** [comment]
Hi @zkonge,

there's no specific reason why `from_value` wasn't added yet I didn't need it yet and nobody complained either :wink:.

Would you like to provide a PR to add it?

**Comment by martinohmann** [comment]
I'd probably go with the `DeserializeOwned` trait bound, similar to what `serde_json` does since we'll not borrow data from the deserializer here.
