### ISSUE TITLE
[Question] parsing a block that may appear one or several times

### ISSUE THREAD

**Issue by Armael** [martinohmann/hcl-rs#380]
Hi! Thanks for this library. I am trying to parse a HCL file with the following shape, where a `task` may contain one or several `service` blocks (with no labels):

```
task "abc" {
  service {
    name = "a"
  }

  service {
    name = "b"
  }
}

task "def" {
  service {
    name = "c"
  }
}
```

I tried to use the following Rust types, but this doesn't seem to work (I get `invalid type: map, expected a sequence`). 
It looks like in the first task, `service` is a sequence (so `Vec` works), but in the second task, it is directly inlined as a field, and I don't know how to support both cases.

```rust
#[derive(Deserialize, Debug)]
struct Config {
    #[serde(rename = "task")]
    tasks: hcl::Map<String, Task>,
}

#[derive(Deserialize, Debug)]
struct Task {
    #[serde(rename = "service")]
    services: Vec<Service>,
}

#[derive(Deserialize, Debug)]
struct Service {
    name: String,
}
```

Is there some trick I'm missing that could help to make this work?

**Comment by martinohmann** [comment]
Hi there @Armael, you could use a custom deserializer to achieve what you want, here's an example that deserializes a `Vec<T>` and a `T` (which will be converted into a `Vec<T>` with a single element):

```rust
use serde::de::{
    value::{MapAccessDeserializer, SeqAccessDeserializer},
    MapAccess, SeqAccess, Visitor,
};
use serde::{Deserialize, Deserializer};
use std::fmt;
use std::marker::PhantomData;

fn vec_or_map<'de, T, D>(deserializer: D) -> Result<Vec<T>, D::Error>
where
    T: Deserialize<'de>,
    D: Deserializer<'de>,
{
    struct VecOrMap<T>(PhantomData<fn() -> T>);

    impl<'de, T> Visitor<'de> for VecOrMap<T>
    where
        T: Deserialize<'de>,
    {
        type Value = Vec<T>;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("sequence or map")
        }

        fn visit_seq<A>(self, seq: A) -> Result<Self::Value, A::Error>
        where
            A: SeqAccess<'de>,
        {
            Deserialize::deserialize(SeqAccessDeserializer::new(seq))
        }

        fn visit_map<M>(self, map: M) -> Result<Self::Value, M::Error>
        where
            M: MapAccess<'de>,
        {
            Deserialize::deserialize(MapAccessDeserializer::new(map)).map(|value| vec![value])
        }
    }

    deserializer.deserialize_any(VecOrMap(PhantomData))
}
```

And then you would use it like this on your `Task` type:

```rust
#[derive(Deserialize, Debug)]
struct Task {
    #[serde(rename = "service", deserialize_with = "vec_or_map")]
    services: Vec<Service>,
}
```

There's also a similar example in the serde docs: https://serde.rs/string-or-struct.html

Let me know if this works for you.

**Comment by Armael** [comment]
Thanks a lot for the detailed answer and code snippet, this does the job perfectly!

**Comment by martinohmann** [comment]
@Armael There's also `OneOrMany` which is provided by the popular `serde_with` crate that you could use here instead of relying on custom code: https://docs.rs/serde_with/3.11.0/serde_with/struct.OneOrMany.html
