### ISSUE TITLE
Is evalulating expressions supported?

### ISSUE THREAD

**Issue by korewaChino** [martinohmann/hcl-rs#50]
Hi! I'm just wondering if evaulating expressions are supported or even in scope for `hcl-rs`?

Currently, I want to serialize a HCL config with expressions into a file, but seems like the value just returns a literal string of the raw expression.

Is expression support going to be in hcl-rs?

**Comment by martinohmann** [comment]
@korewaChino I'm currently working on implementing the full set of expressions into the `Expression` enum, e.g. `Template`, `Conditional`, `ForExpr`, `Operation` etc. Right now these are just treated as `RawExpression`. When this is done I'm also planning to support expression evaluation.

**Comment by martinohmann** [comment]
@korewaChino FYI, after #55 is merged, I'll be able to implement the full set of HCL expressions including the HCL string templating language. I already have some branches waiting to be rebased because of #55 and the internal rewrite.

**Comment by martinohmann** [comment]
@korewaChino Expression and template evaluation was released yesterday as part of the 0.9.0 release. Have a look at the docs of the `eval` module to see how it's used: https://docs.rs/hcl-rs/latest/hcl/eval/index.html

Please note that the 0.9.0 contains some breaking changes. They are documented in the changelog: https://github.com/martinohmann/hcl-rs/blob/main/CHANGELOG.md
