### ISSUE TITLE
Panic attempting to parse an integer

### ISSUE THREAD

**Issue by archoversight** [martinohmann/hcl-rs#83]
Given the following HCL:

```
resource "test" "testing" {
  ids      = [module.instance.0.id]
}
```

It leads to this panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/hcl-rs-0.8.2/src/parser/mod.rs:342:32
```

**Comment by martinohmann** [comment]
Hi! Thanks for reporting this. I had a quick look at the relevant code and already spotted the issue. Will try to provide a fix later today.

**Comment by martinohmann** [comment]
@archoversight  I just published https://crates.io/crates/hcl-rs/0.8.4 which includes the fix.

**Comment by archoversight** [comment]
@martinohmann thank you!
